/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class readdy_impl_sim_top_TopMM */

#ifndef _Included_readdy_impl_sim_top_TopMM
#define _Included_readdy_impl_sim_top_TopMM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     readdy_impl_sim_top_TopMM
 * Method:    cCreateSimulation
 * Signature: (ZLjava/lang/String;Ljava/lang/String;IDDDDD[DI[D[D[D[D[FI[I)V
 */
JNIEXPORT void JNICALL Java_readdy_impl_sim_top_TopMM_cCreateSimulation
  (JNIEnv *, jobject, jboolean, jstring, jstring, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdoubleArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jfloatArray, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
